apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
     targetNamespace: metallb-system
     install:
       createNamespace: true           # ADD this
       remediation: { retries: 3 }
      chart: metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    # your values here (e.g., address pools)
