# infra/network/cilium/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  releaseName: cilium               # release name Helm will use
  targetNamespace: kube-system
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: cilium
      version: 1.17.8
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 10m
  install:
    crds: Create
    remediation: { retries: 3 }
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
    resetValues: true
uninstall:
    keepHistory: false
  driftDetection:
    mode: enabled

  values:
    # keep kube-proxy on for now
    kubeProxyReplacement: "disabled"

    ipam:
      mode: kubernetes

    routingMode: tunnel
    tunnelProtocol: vxlan

    # Talos-friendly cgroup settings
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    operator:
      replicas: 1

    hubble:
      enabled: true
      relay: { enabled: true }
      ui: { enabled: true }
