apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium            # keep this if this is the HR name you committed
  namespace: flux-system
spec:
  # Tell Flux to manage the *existing* helm release name it adopted earlier:
  releaseName: kube-system-cilium   # <- matches your Helm history

  targetNamespace: kube-system
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: cilium
      version: 1.17.8
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 10m
  install:
    crds: Create
    remediation: { retries: 3 }
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  uninstall:
    keepHistory: false
  driftDetection:
    mode: enabled

  values:
    # Use boolean false (you currently have the string "false")
    kubeProxyReplacement: false

    ipam:
      mode: kubernetes

    routingMode: tunnel
    tunnelProtocol: vxlan

    # Talos-safe cgroup config
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    # Let chart defaults set capabilities (avoid schema/runtime clashes)
    securityContext:
      capabilities:
        ciliumAgent: {}
        cleanCiliumState: {}

    # Single node: one operator
    operator:
      replicas: 1

    # Hubble as you had it
    hubble:
      enabled: true
      relay: { enabled: true }
      ui: { enabled: true }
