# infra/network/cilium/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.17.8
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  targetNamespace: kube-system
  install:
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
  timeout: 10m
  values:
    ipam:
      mode: kubernetes
    kubeProxyReplacement: "false"   # keep this since kube-proxy is still there
    routingMode: tunnel               # <- replaces old `tunnel` flag
    tunnelProtocol: vxlan             # <- replaces `tunnel: vxlan`
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
