spec:
  targetNamespace: kube-system
  install:
    createNamespace: true
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
  timeout: 10m
  values:
    ipam:
      mode: kubernetes

    # keep kube-proxy for now
    kubeProxyReplacement: false

    # new keys since 1.15+
    routingMode: tunnel
    tunnelProtocol: vxlan

    # Talos-friendly bits
    cgroup:
      autoMount: false
      hostRoot: /sys/fs/cgroup
    securityContext:
      capabilities:
        ciliumAgent:
          drop: [ "SYS_MODULE" ]
        cleanCiliumState:
          drop: [ "SYS_MODULE" ]

    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
