apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  releaseName: kube-system-cilium          # must match your live release
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.17.8
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled

  # Talos-friendly values that match what you just installed
  values:
    # Talk directly to your API server (prevents ClusterIP bootstrap issues)
    k8sServiceHost: "192.168.1.155"
    k8sServicePort: 6443

    # Keep kube-proxy; safer baseline
    kubeProxyReplacement: "false"          # string avoids the chart's required() gotcha

    # Standard IPAM
    ipam:
      mode: kubernetes

    # Default datapath is fine; explicitly set tunnel if you prefer
    routingMode: tunnel

    # Talos cgroup settings
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    # Reduce moving parts while stabilizing
    hubble:
      enabled: false

    # Extra caps commonly used on Talos to pass PSA/host restrictions
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
