apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: plex
spec:
  accessModes: [ ReadOnlyMany ]
  resources: { requests: { storage: 10Ti } }
  volumeName: plex-media-pv
  storageClassName: ""    # use pre-bound PV
