cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
hubble:
  enabled: false
ipam:
  mode: kubernetes
k8sServiceHost: 192.168.1.155
k8sServicePort: 6443
kubeProxyReplacement: false
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
routingMode: tunnel
hubble:
  enabled: false
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
