apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-2rep
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-3rep
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
