apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  targetNamespace: traefik
  interval: 30m
  timeout: 15m
  install:
    createNamespace: true
    crds: Create
    remediation: { retries: 3 }
  upgrade:
    crds: CreateReplace
    remediation: { remediateLastFailure: true, retries: 3 }
  chart:
    spec:
      chart: traefik
      version: 28.0.0         # v3 chart series; pin something current and stable
      sourceRef:
        kind: HelmRepository
        name: traefik         # must exist in sources/helm/
        namespace: flux-system
      interval: 30m
  values:
    # Expose it via MetalLB
    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Cluster
      # (optional) annotations to pick a specific MetalLB pool/IP can go here

    # Use standard Kubernetes Ingress (no Traefik CRDs needed at first)
    providers:
      kubernetesIngress:
        enabled: true
      kubernetesCRD:
        enabled: false

    ingressClass:
      enabled: true
      isDefaultClass: true

    # --- PodSecurity "restricted" friendly bits ---
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      fsGroup: 65532

    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ "ALL" ]

    logs:
      general:
        level: INFO
      access:
        enabled: true

    deployment:
      replicas: 1
      # schedule on your single node regardless of taints (harmless if none)
      tolerations:
        - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
