apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-vip
  namespace: kube-system
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.160
  externalTrafficPolicy: Cluster
  ports:
    - name: https
      port: 6443
      targetPort: 6443
  # NOTE: no selector on purpose
