apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonLabels:
  app.kubernetes.io/name: kube-apiserver-vip

resources:
  - kube-apiserver-vip.yaml
  - kube-apiserver-vip-endpointslice.yaml  # or endpointslice.yaml if you switch
