apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system            # <-- CR lives here
spec:
  targetNamespace: longhorn-system  # <-- chart installs here
  interval: 30m
  install:
    createNamespace: true           # <-- let Helm create target ns
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
  chart:
    spec:
      chart: longhorn
      version: 1.9.2
      sourceRef:
        kind: HelmRepository
        name: longhorn              # must match your helmrepo.yaml
        namespace: flux-system
  values:
    defaultSettings:
      defaultReplicaCount: 2          # adjust for number of nodes
      createDefaultDiskLabeledNodes: false
