apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system           # HR lives in flux-system
spec:
  targetNamespace: cert-manager    # chart installs here
  interval: 30m
  timeout: 10m
  install:
    createNamespace: true
    crds: Create                   # let Flux manage CRDs too
    remediation: { retries: 3 }
  upgrade:
    crds: CreateReplace
    remediation: { remediateLastFailure: true, retries: 3 }
  chart:
    spec:
      chart: cert-manager
      version: 1.15.3              # pin a stable version (adjust when you’re ready)
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 30m
  values:
    # IMPORTANT: For the Jetstack chart, the correct key is installCRDs (not crds.enabled)
    installCRDs: true
    # Optional niceties
    replicaCount: 2
    prometheus:
      enabled: false
