apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system              # <-- CR lives here
spec:
  targetNamespace: cert-manager       # <-- chart installs here
  interval: 30m
  install:
    createNamespace: true             # <-- create the target ns automatically
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: cert-manager
      version: <your-version>
      sourceRef:
        kind: HelmRepository
        name: cert-manager            # must match your helmrepo.yaml
        namespace: flux-system
  values:
    crds:
      enabled: true
