apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/kube-system/coredns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system    # <-- replace with your GitRepository name
    namespace: flux-system
  targetNamespace: kube-system
  wait: true
