apiVersion: v1
kind: Secret
metadata:
    name: influxdb-init
    namespace: influxdb
type: Opaque
stringData:
    DOCKER_INFLUXDB_INIT_MODE: ENC[AES256_GCM,data:UM8kp8A=,iv:65ILEh55EWpVfrK4LGR2R4dC4H6A4KgoQVLph4CiZNQ=,tag:nHECrcafaRw5XKjVzLg4fw==,type:str]
    DOCKER_INFLUXDB_INIT_USERNAME: ENC[AES256_GCM,data:CovMRug=,iv:sKlyz8NNrMZuPu1nkzRFWBoJfnCCVSa9GN6WmxGefkg=,tag:TZDoW7uD5mjkcjHIfPiXwA==,type:str]
    DOCKER_INFLUXDB_INIT_PASSWORD: ENC[AES256_GCM,data:eZkdTyByPDHz6GT87/uYWZtocm+P6tSMl4mzgxGs57ubH+GuoPEcH7SD5TzikQd7bQ==,iv:kl+K3zBKYSpdi0adBrGDcxNoDTLgNxm5zjsOOe47bNM=,tag:2u0Pg+DZYlBIsr72PyhLCA==,type:str]
    DOCKER_INFLUXDB_INIT_ORG: ENC[AES256_GCM,data:t6ZE7eg8,iv:stmZ73on8WjDsToEwG/8SZwHYQTCRNXWUggu/uBR6DI=,tag:wdnvqdTGMU+U0B+lwhd8Og==,type:str]
    DOCKER_INFLUXDB_INIT_BUCKET: ENC[AES256_GCM,data:eIBF5mTrEg==,iv:/xtr3hQm3/QXL1HEHldc+YkR6mFDaGB4sWvNoXCqH4E=,tag:85cS+Opxh0UBnjLipRu0Zg==,type:str]
    DOCKER_INFLUXDB_INIT_RETENTION: ENC[AES256_GCM,data:8mTA,iv:pjAoFpxVOoUJr3yxKtmYykxrqSKh1VQuScbYk7z5hug=,tag:SDo5+nwRguNNH7oT4K9jTQ==,type:str]
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ENC[AES256_GCM,data:APF2MufUaZ+ipg5rW54hRjtuTfq5QfSddUXp9oa0XoX3ctzAW0ad5Y0HpiZk5s7pi3IIznxoZ5GCWvw+rl/51S+oNUTb0vwefwaEuClI280E,iv:58IV9M32LlMSIn49C1hkAeUfxV/YdiNywlEif3wWFv0=,tag:VdSZcGbK8S4l8go9LrJ7YA==,type:str]
sops:
    age:
        - recipient: age185ha9svcn30xe0avxje8ct70k727rrsc44lv0z452mjf7vsduaqs43e9jt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRzNvUmtibTNDZk41V29x
            THM2Rm4yRFBPZGVyZ1dhL0dZVFM4ODIycUZNCkZmVENVdG5uVkZpbFhvaWk1UUFZ
            NGtwa2kybEVEQjV6Zmtlb3AvdVQwZTgKLS0tIGVWZm5sT3h6MVQ3clYrdE9zbk9K
            dEVpWGxDa2tzZ0k4K0YyZ1ZFdVdDaFEK60JdNFtYjENgPnDc2jkBWz9QQlDrBey8
            wN0pEHJK0iYLVu60OBcKo1q2NRhrefZsV6gBKvFDJyaIf/G5gi7xqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T14:31:14Z"
    mac: ENC[AES256_GCM,data:lNSTNzAMDrMZ7CV+26cLA7+Xo2QtiEeeWVhJRSsT+xOtxINBsR+pd9/252dY7utiuO7T4PtQQIP9Iop8FuldPxlf7mdetCnPnoXRJY/6M7CYg5StA+Mte9sdcFQ8NMb/QajK+mq281U9IknnwVSCCnpd5gK6xFGwgDP6tJNusOk=,iv:snMGrXzQSctJb8tC8GA/zexO/hiZfxxV4piS47yb8Q8=,tag:R9S+RxyTw8uSAIyn5zOW7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
