apiVersion: v1
kind: Secret
metadata:
  name: influxdb-init
  namespace: influxdb
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  DOCKER_INFLUXDB_INIT_PASSWORD: "{{REPLACE_WITH_$INFLUX_PASS}}"
  DOCKER_INFLUXDB_INIT_ORG: dozzly
  DOCKER_INFLUXDB_INIT_BUCKET: homelab
  DOCKER_INFLUXDB_INIT_RETENTION: 30d
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{REPLACE_WITH_$INFLUX_TOKEN}}"
