apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: { name: intel-device-plugins-operator, namespace: kube-system }
spec:
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.34.0
      sourceRef: { kind: HelmRepository, name: intel, namespace: flux-system }
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: { name: intel-gpu-plugin, namespace: kube-system }
spec:
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.34.0
      sourceRef: { kind: HelmRepository, name: intel, namespace: flux-system }
  values:
    nodeSelector: { kubernetes.io/arch: amd64 }
    tolerations: []   # add if your NUCs are tainted
