apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

commonLabels:
  app.kubernetes.io/part-of: metallb

resources:
  - namespace.yaml
  - ipaddresspool.yaml
  - l2advertisement.yaml
