apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: coredns
      version: 1.28.0 # or your repo’s latest; keep stable
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  values:
    replicaCount: 2

    # IMPORTANT: do NOT use host networking
    hostNetwork: false
    # Let pods use normal ClusterFirst DNS
    dnsPolicy: ClusterFirst

    service:
      name: kube-dns
      type: ClusterIP
      # preserve the clusterIP; otherwise Helm may try to change it
      clusterIP: ${KUBE_DNS_IP}

    # If your chart manages the Corefile, uncomment the block below and remove the ConfigMap from step 3:
    # servers:
    #   - zones:
    #       - zone: .
    #     port: 53
    #     plugins:
    #       - name: errors
    #       - name: health
    #         parameters: { lameduck: 5s }
    #       - name: ready
    #       - name: kubernetes
    #         parameters: cluster.local in-addr.arpa ip6.arpa
    #         configBlock: |
    #           pods insecure
    #           fallthrough in-addr.arpa ip6.arpa
    #           ttl 30
    #       - name: prometheus
    #         parameters: :9153
    #       - name: forward
    #         parameters: . /etc/resolv.conf
    #       - name: cache
    #         parameters: 30
    #       - name: loop
    #       - name: reload
    #       - name: loadbalance

    resources:
      requests:
        cpu: 100m
        memory: 70Mi
      limits:
        memory: 170Mi

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: k8s-app
                    operator: In
                    values: ["kube-dns"]
              topologyKey: kubernetes.io/hostname
