apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: coredns
      version: 1.43.3                 # pick a stable version available in your repo
      sourceRef:
        kind: HelmRepository
        name: coredns                # or your chosen repo
        namespace: flux-system
  values:
    replicaCount: 2
    hostNetwork: false
    dnsPolicy: Default
    image:
      repository: registry.k8s.io/coredns/coredns
      tag: v1.11.1

    service:
      name: kube-dns
      type: ClusterIP
      clusterIP: 10.96.0.10          # keep your current ClusterIP

    # Corefile managed by values — adjust to match the working one
    servers:
      - zones: [ { zone: "." } ]
        port: 53
        plugins:
          - name: errors
          - name: health
            parameters: { lameduck: 5s }
          - name: ready
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          - name: prometheus
            parameters: :9153
          - name: forward
            parameters: . 1.1.1.1 1.0.0.1 9.9.9.9
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
