apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coredns-deploy.yaml
# If your chart does NOT own the Corefile, include the ConfigMap we applied in step 3:
#  - corefile-configmap.yaml
