apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
  replicas: 3
  template:
    spec:
      # Allow CoreDNS to run on all control-plane nodes (incl. warner’s custom taint)
      tolerations:
        - key: role
          operator: Equal
          value: admin
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule

      # Prefer one pod per node (soft; won’t block scheduling if a node is down)
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    k8s-app: kube-dns

      # Make sure no old nodeSelector pins it away from warner
      nodeSelector: {}
      # If you *want* to pin only to gee+goldstone, s
