apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: { name: intel-device-plugins-operator, namespace: flux-system }
spec:
  targetNamespace: intel-device-plugins # pick your desired ns
  install:
    createNamespace: true           # ADD this
    remediation: { retries: 3 }
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.34.0
      sourceRef: { kind: HelmRepository, name: intel, namespace: flux-system }
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: { name: intel-gpu-plugin, namespace: flux-system }
spec:
  targetNamespace: intel-device-plugins # pick your desired ns
  install:
    createNamespace: true           # ADD this
    remediation: { retries: 3 }
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.34.0
      sourceRef: { kind: HelmRepository, name: intel, namespace: flux-system }
  values:
    nodeSelector: { kubernetes.io/arch: amd64 }
    tolerations: []   # add if your NUCs are tainted
